### ISSUE TITLE
Can't get email/SMTP to work

### ISSUE THREAD

**Issue by chooko** [adamcooke/staytus#160]
Hey there,

Trying to get this implemented internally. I think I have SMTP setup right in the environment.yml file, but I still get errors when trying to send email. 

Not sure what to grep for in production.log, but in worker.log I see this error: 
Worker: Starting job worker
Worker: Exiting...
`/home/myuser` is not writable.
Bundler will use `/tmp/bundler/home/myuser` as your home directory temporarily.

Is this what's causing the issue?

**Comment by freibuis** [comment]
if you are using something like heroku.. I would suggest not putting that information into the environment.yml file but adding it as a ENV instead.. good idea to keep secrets out of source control.

the problem that you are having is more likely to do with the smtp server that you are trying to send to...

test it by doing this on the server that is having the issue
rails console
> s = Subscriber.last  (or the user you want to test for)
>s.send_verification_email (just remember doing this will send that user an email)

this will then try to send the email and will give you there error right there for you to debug

btw the error `/home/myuser is not writable.` is most likey because you are starting the process as the wrong user  and it does not have permission to access that users home directory to write (or access bundler properly)

**Comment by chooko** [comment]
Running the s.send_verification_email spits out:
`NoMethodError: undefined method 'send_verification_email' for "email@email.net":String`

I'm beginning to wonder if something compiled incorrectly?

**Comment by chooko** [comment]
Using s = Subscriber.last, I get the following error on send_verification_email:
`NameError: uninitialized constant Staytus::Email
Did you mean? Premailer
                          Mail
                       from app/models/subscriber.rb:41: in 'send_verification_email"
                       from (irb):2`

**Comment by freibuis** [comment]
I guess you are using the master branch? that will not work in rails 5.1 

I would try pulling the stable branch.

**Comment by chooko** [comment]
I used this command to clone the repo to my box initially:
`sudo -u staytus git clone https://github.com/adamcooke/staytus /opt/staytus/staytus`

What should I use instead to pull stable branch?

**Comment by freibuis** [comment]
`sudo -u staytus git clone -b stable https://github.com/adamcooke/staytus /opt/staytus/staytus `

**Comment by chooko** [comment]
Interesting. After installing from stable branch, I added an email to the subscribers list, and everything came back green, but the email was not sent (likely because of credential mismatch or similar issue on SMTP server). However, any subsequent try to add an email to the list results in an HTTP 500 POST. 

Running rails console errors out after some error about a secret token.

**Comment by chooko** [comment]
Got rails console running by installing an additional package. Still getting 500 POST when I add an email to subscriber list.

rails console is showing connection refused to my SMTP server.

**Comment by freibuis** [comment]
whats the output when you try to send the verication email
```
s = Subscriber.last
s.send_verification_email ```

the error there will be able to tell me if it is STMP related

**Comment by chooko** [comment]
Depending on how I change the SMTP settings it's either:

`OpenSSL::SSL::SSLError : hostname "server.domain.net" does not match the server certificate`

or
`Errno::ECONNREFUSED: Connection refused - connect(2) for "server.domain.net" port 25`

**Comment by freibuis** [comment]
ok I took a peek into the smtp initializer and this is what it has
```ruby
  ActionMailer::Base.smtp_settings = {
    :address                => ENV['STAYTUS_SMTP_HOSTNAME'],
    :port                   => ENV['STAYTUS_SMTP_PORT'],
    :user_name              => ENV['STAYTUS_SMTP_USERNAME'],
    :password               => ENV['STAYTUS_SMTP_PASSWORD'],
    :authentication         => ENV['STAYTUS_SMTP_AUTH_MODE'],
    :enable_starttls_auto   => ENV['STAYTUS_SMTP_STARTTLS'] == '1'
  }
```
you will need to add this (i will create a pull request today for it) to the [config/initializers/smtp.rb](config/initializers/smtp.rb)

add this (info from http://api.rubyonrails.org/classes/ActionMailer/Base.html)
```ruby
::openssl_verify_mode   => ENV['STAYTUS_SMTP_VERIFY_SSL'] == OpenSSL::SSL::VERIFY_PEER
```

then add environmental variable STAYTUS_SMTP_VERIFY_SSL= OpenSSL::SSL::VERIFY_NONE    (or 'none')


now for your first issue...  could be that your smtp server doesnt allow to be connected to send mail over port 25. I would suggest setting STAYTUS_SMTP_STARTTLS and change the port (STAYTUS_SMTP_PORT) to either 465 or 587 (check your smtp admin)

**Comment by chooko** [comment]
Thank you for your help on this. It seems that this will be the fix.

I think we're good to close this now.
